name: Notification

on:
  release:

jobs:
  notify-staging:
    if: github.event.release.prerelease == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: "Ilshidur/action-discord@0.4.0"
        with:
          args: 'OKL Launcher v${{ github.event.release.tag_name }} - [Download](${{ github.event.release.html_url }})'
        env:
          DISCORD_WEBHOOK: ${{ secrets.STAGING_DISCORD_WEBHOOK }}

  notify-production:
    if: github.event.release.draft == 'false' && github.event.release.prerelease == 'false'
    runs-on: ubuntu-latest

    steps:
      - uses: "Ilshidur/action-discord@0.4.0"
        with:
          args: 'OKL Launcher v${{ github.event.release.tag_name }} - [Download](${{ github.event.release.html_url }})'
        env:
          DISCORD_WEBHOOK: ${{ secrets.PRODUCTION_DISCORD_WEBHOOK }}
